//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeHelper.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErogeHelper.Language.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eroge Helper.
        /// </summary>
        public static string About_AppName {
            get {
                return ResourceManager.GetString("About.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string About_Contributors {
            get {
                return ResourceManager.GetString("About.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string About_Dependencies {
            get {
                return ResourceManager.GetString("About.Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find any bugs, please open a new issue in the github repository..
        /// </summary>
        public static string About_FileABug {
            get {
                return ResourceManager.GetString("About.FileABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About.GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new issue.
        /// </summary>
        public static string About_OpenNewIssue {
            get {
                return ResourceManager.GetString("About.OpenNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : .
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Card.
        /// </summary>
        public static string CardControl_CloseTip {
            get {
                return ResourceManager.GetString("CardControl.CloseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text.
        /// </summary>
        public static string CardControl_SelectTextTip {
            get {
                return ResourceManager.GetString("CardControl.SelectTextTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Center.
        /// </summary>
        public static string GameView_ActionCenter {
            get {
                return ResourceManager.GetString("GameView.ActionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Focus
        ///(If you can&apos;t click when play game full screen. Turn on this).
        /// </summary>
        public static string GameView_FocusTip {
            get {
                return ResourceManager.GetString("GameView.FocusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease size.
        /// </summary>
        public static string GameView_FontDecreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontDecreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase size.
        /// </summary>
        public static string GameView_FontIncreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontIncreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip too long text.
        /// </summary>
        public static string GameView_MaxLenthTip {
            get {
                return ResourceManager.GetString("GameView.MaxLenthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin Japanese text.
        /// </summary>
        public static string GameView_PinnedTip {
            get {
                return ResourceManager.GetString("GameView.PinnedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string GameView_Preference {
            get {
                return ResourceManager.GetString("GameView.Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot.
        /// </summary>
        public static string GameView_ScreenShot {
            get {
                return ResourceManager.GetString("GameView.ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen (Alt+Enter).
        /// </summary>
        public static string GameView_SwitchFullScreen {
            get {
                return ResourceManager.GetString("GameView.SwitchFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window (Alt + Enter).
        /// </summary>
        public static string GameView_SwitchWindow {
            get {
                return ResourceManager.GetString("GameView.SwitchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task View.
        /// </summary>
        public static string GameView_TaskView {
            get {
                return ResourceManager.GetString("GameView.TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Japanese text.
        /// </summary>
        public static string GameView_UnpinTip {
            get {
                return ResourceManager.GetString("GameView.UnpinTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        public static string GameView_VolumeDecreaseTip {
            get {
                return ResourceManager.GetString("GameView.VolumeDecreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        public static string GameView_VolumeIncreaseTip {
            get {
                return ResourceManager.GetString("GameView.VolumeIncreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show other texts.
        /// </summary>
        public static string GeneralPage_AppendText {
            get {
                return ResourceManager.GetString("GeneralPage.AppendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string GeneralPage_Brightness {
            get {
                return ResourceManager.GetString("GeneralPage.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would change the gamma value.
        /// </summary>
        public static string GeneralPage_BrightnessTip {
            get {
                return ResourceManager.GetString("GeneralPage.BrightnessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepL Client Extention.
        /// </summary>
        public static string GeneralPage_DeepL {
            get {
                return ResourceManager.GetString("GeneralPage.DeepL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download DeepL.
        /// </summary>
        public static string GeneralPage_DeepLDownload {
            get {
                return ResourceManager.GetString("GeneralPage.DeepLDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSIC.
        /// </summary>
        public static string GeneralPage_Msic {
            get {
                return ResourceManager.GetString("GeneralPage.Msic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralPage_Title {
            get {
                return ResourceManager.GetString("GeneralPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eroge Helper - Hook Config.
        /// </summary>
        public static string HookConfig_Title {
            get {
                return ResourceManager.GetString("HookConfig.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input HCode or RCode.
        /// </summary>
        public static string HookPage_CodeInsertDialogTip {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertDialogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string HookPage_CodeInsertLabel {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HookPage_CodeSearchCancel {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string HookPage_CodeSearchNoResult {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search code on Aniclan.
        /// </summary>
        public static string HookPage_CodeSearchTip {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Output.
        /// </summary>
        public static string HookPage_Console {
            get {
                return ResourceManager.GetString("HookPage.Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Code.
        /// </summary>
        public static string HookPage_HookCode {
            get {
                return ResourceManager.GetString("HookPage.HookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string HookPage_Insert {
            get {
                return ResourceManager.GetString("HookPage.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Code.
        /// </summary>
        public static string HookPage_RCodeLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text help find out read code.
        /// </summary>
        public static string HookPage_RCodeTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegExp.
        /// </summary>
        public static string HookPage_RegExp {
            get {
                return ResourceManager.GetString("HookPage.RegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete characters before &apos;「&apos; or &apos;『&apos;.
        /// </summary>
        public static string HookPage_RegExpTag1 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete characters after &apos;」&apos; or &apos;』&apos;.
        /// </summary>
        public static string HookPage_RegExpTag2 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ruby like &lt;.*?&gt;.
        /// </summary>
        public static string HookPage_RegExpTag3 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete linebreaks.
        /// </summary>
        public static string HookPage_RegExpTag4 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete any Ascii chractors.
        /// </summary>
        public static string HookPage_RegExpTag5 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up a RegExp.
        /// </summary>
        public static string HookPage_RegExpTip {
            get {
                return ResourceManager.GetString("HookPage.RegExpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Text.
        /// </summary>
        public static string HookPage_SelectedText {
            get {
                return ResourceManager.GetString("HookPage.SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide down to select a text thread.
        /// </summary>
        public static string HookPage_SelectedTextInitTip {
            get {
                return ResourceManager.GetString("HookPage.SelectedTextInitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Text.
        /// </summary>
        public static string HookPage_SelectText {
            get {
                return ResourceManager.GetString("HookPage.SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string HookPage_Submit {
            get {
                return ResourceManager.GetString("HookPage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string HookPage_Text {
            get {
                return ResourceManager.GetString("HookPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HookPage_TextThreadRefreshLabel {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all text thread.
        /// </summary>
        public static string HookPage_TextThreadRefreshTip {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook Config.
        /// </summary>
        public static string HookPage_Title {
            get {
                return ResourceManager.GetString("HookPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will register Eroge Helper to the window context menu for &quot;.exe&quot; suffix programs. Please uninstall me before move or delete..
        /// </summary>
        public static string Installer_Info {
            get {
                return ResourceManager.GetString("Installer.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Installer_Register {
            get {
                return ResourceManager.GetString("Installer.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        public static string Installer_Unload {
            get {
                return ResourceManager.GetString("Installer.Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dict.
        /// </summary>
        public static string MeCabPage_Dict {
            get {
                return ResourceManager.GetString("MeCabPage.Dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuriganaBottom.
        /// </summary>
        public static string MeCabPage_FuriganaBottom {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MecabPage.FuriganaDefault.
        /// </summary>
        public static string MeCabPage_FuriganaDefault {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacabPage.FuriganaTop.
        /// </summary>
        public static string MeCabPage_FuriganaTop {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furigana display type.
        /// </summary>
        public static string MeCabPage_FuriganaType {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiragana.
        /// </summary>
        public static string MeCabPage_Hiragana {
            get {
                return ResourceManager.GetString("MeCabPage.Hiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show japanese text.
        /// </summary>
        public static string MeCabPage_JapaneseText {
            get {
                return ResourceManager.GetString("MeCabPage.JapaneseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katakana.
        /// </summary>
        public static string MeCabPage_Katakana {
            get {
                return ResourceManager.GetString("MeCabPage.Katakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text dispaly position.
        /// </summary>
        public static string MeCabPage_PositionFormat {
            get {
                return ResourceManager.GetString("MeCabPage.PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romaji.
        /// </summary>
        public static string MeCabPage_Romaji {
            get {
                return ResourceManager.GetString("MeCabPage.Romaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Flyout.
        /// </summary>
        public static string MeCabPage_TextFlyout {
            get {
                return ResourceManager.GetString("MeCabPage.TextFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MecabPage.TextVertical.
        /// </summary>
        public static string MeCabPage_TextVertical {
            get {
                return ResourceManager.GetString("MeCabPage.TextVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mecab.
        /// </summary>
        public static string MeCabPage_Title {
            get {
                return ResourceManager.GetString("MeCabPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout! Game window not found.
        /// </summary>
        public static string MessageBox_TimeoutInfo {
            get {
                return ResourceManager.GetString("MessageBox.TimeoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject.
        /// </summary>
        public static string SelectProcess_InjectButton {
            get {
                return ResourceManager.GetString("SelectProcess.InjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Application.
        /// </summary>
        public static string SelectProcess_Label {
            get {
                return ResourceManager.GetString("SelectProcess.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process has gone.
        /// </summary>
        public static string SelectProcess_ProcessExit {
            get {
                return ResourceManager.GetString("SelectProcess.ProcessExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use ErogeHelper.Installer.exe to install me~.
        /// </summary>
        public static string SelectProcess_Tips {
            get {
                return ResourceManager.GetString("SelectProcess.Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eroge Helper - Select Process.
        /// </summary>
        public static string SelectProcess_Title {
            get {
                return ResourceManager.GetString("SelectProcess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Run as Administrator.
        /// </summary>
        public static string ShellMenu_Administrator {
            get {
                return ResourceManager.GetString("ShellMenu.Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string ShellMenu_DirectStart {
            get {
                return ResourceManager.GetString("ShellMenu.DirectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Locate Emulator Start.
        /// </summary>
        public static string ShellMenu_LEStart {
            get {
                return ResourceManager.GetString("ShellMenu.LEStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textractor: already injected.
        /// </summary>
        public static string Textractor_AlreadyInject {
            get {
                return ResourceManager.GetString("Textractor.AlreadyInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Textractor_Clipboard {
            get {
                return ResourceManager.GetString("Textractor.Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textractor: initialization completed.
        /// </summary>
        public static string Textractor_Init {
            get {
                return ResourceManager.GetString("Textractor.Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textractor: couldn&apos;t inject.
        /// </summary>
        public static string Textractor_InjectFailed {
            get {
                return ResourceManager.GetString("Textractor.InjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textractor: invalid code.
        /// </summary>
        public static string Textractor_InvalidCode {
            get {
                return ResourceManager.GetString("Textractor.InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textractor: invalid process.
        /// </summary>
        public static string Textractor_InvalidProcess {
            get {
                return ResourceManager.GetString("Textractor.InvalidProcess", resourceCulture);
            }
        }
    }
}
