//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeHelper.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErogeHelper.Language.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Eroge Helper 的本地化字符串。
        /// </summary>
        public static string About_AppName {
            get {
                return ResourceManager.GetString("About.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About.Contributors 的本地化字符串。
        /// </summary>
        public static string About_Contributors {
            get {
                return ResourceManager.GetString("About.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About.Dependencies 的本地化字符串。
        /// </summary>
        public static string About_Dependencies {
            get {
                return ResourceManager.GetString("About.Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About.FileABug 的本地化字符串。
        /// </summary>
        public static string About_FileABug {
            get {
                return ResourceManager.GetString("About.FileABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About.GitHub 的本地化字符串。
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About.GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About.OpenNewIssue 的本地化字符串。
        /// </summary>
        public static string About_OpenNewIssue {
            get {
                return ResourceManager.GetString("About.OpenNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About.Version 的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installer.Info 的本地化字符串。
        /// </summary>
        public static string Installer_Info {
            get {
                return ResourceManager.GetString("Installer.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string Installer_Register {
            get {
                return ResourceManager.GetString("Installer.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unload 的本地化字符串。
        /// </summary>
        public static string Installer_Unload {
            get {
                return ResourceManager.GetString("Installer.Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageBox.TimeoutInfo 的本地化字符串。
        /// </summary>
        public static string MessageBox_TimeoutInfo {
            get {
                return ResourceManager.GetString("MessageBox.TimeoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject 的本地化字符串。
        /// </summary>
        public static string SelectProcess_InjectButton {
            get {
                return ResourceManager.GetString("SelectProcess.InjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Application 的本地化字符串。
        /// </summary>
        public static string SelectProcess_Lable {
            get {
                return ResourceManager.GetString("SelectProcess.Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectProcess.ViewTips 的本地化字符串。
        /// </summary>
        public static string SelectProcess_Tips {
            get {
                return ResourceManager.GetString("SelectProcess.Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectProcess.ViewTitle 的本地化字符串。
        /// </summary>
        public static string SelectProcess_Title {
            get {
                return ResourceManager.GetString("SelectProcess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Run as Administrator 的本地化字符串。
        /// </summary>
        public static string ShellMenu_Administrator {
            get {
                return ResourceManager.GetString("ShellMenu.Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Game 的本地化字符串。
        /// </summary>
        public static string ShellMenu_DirectStart {
            get {
                return ResourceManager.GetString("ShellMenu.DirectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Locate Emulator Start 的本地化字符串。
        /// </summary>
        public static string ShellMenu_LEStart {
            get {
                return ResourceManager.GetString("ShellMenu.LEStart", resourceCulture);
            }
        }
    }
}
