//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeHelper.Share.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErogeHelper.Share.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SelectProcess_Title {
            get {
                return ResourceManager.GetString("SelectProcess.Title", resourceCulture);
            }
        }
        
        public static string SelectProcess_Tips {
            get {
                return ResourceManager.GetString("SelectProcess.Tips", resourceCulture);
            }
        }
        
        public static string SelectProcess_Label {
            get {
                return ResourceManager.GetString("SelectProcess.Label", resourceCulture);
            }
        }
        
        public static string SelectProcess_InjectButton {
            get {
                return ResourceManager.GetString("SelectProcess.InjectButton", resourceCulture);
            }
        }
        
        public static string MessageBox_TimeoutInfo {
            get {
                return ResourceManager.GetString("MessageBox.TimeoutInfo", resourceCulture);
            }
        }
        
        public static string About_FileABug {
            get {
                return ResourceManager.GetString("About.FileABug", resourceCulture);
            }
        }
        
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About.GitHub", resourceCulture);
            }
        }
        
        public static string About_Contributors {
            get {
                return ResourceManager.GetString("About.Contributors", resourceCulture);
            }
        }
        
        public static string About_Dependencies {
            get {
                return ResourceManager.GetString("About.Dependencies", resourceCulture);
            }
        }
        
        public static string About_OpenNewIssue {
            get {
                return ResourceManager.GetString("About.OpenNewIssue", resourceCulture);
            }
        }
        
        public static string Installer_Info {
            get {
                return ResourceManager.GetString("Installer.Info", resourceCulture);
            }
        }
        
        public static string Installer_Register {
            get {
                return ResourceManager.GetString("Installer.Register", resourceCulture);
            }
        }
        
        public static string Installer_Unload {
            get {
                return ResourceManager.GetString("Installer.Unload", resourceCulture);
            }
        }
        
        public static string HookConfig_Title {
            get {
                return ResourceManager.GetString("HookConfig.Title", resourceCulture);
            }
        }
        
        public static string HookPage_HookCode {
            get {
                return ResourceManager.GetString("HookPage.HookCode", resourceCulture);
            }
        }
        
        public static string HookPage_Insert {
            get {
                return ResourceManager.GetString("HookPage.Insert", resourceCulture);
            }
        }
        
        public static string HookPage_SelectedText {
            get {
                return ResourceManager.GetString("HookPage.SelectedText", resourceCulture);
            }
        }
        
        public static string HookPage_RegExp {
            get {
                return ResourceManager.GetString("HookPage.RegExp", resourceCulture);
            }
        }
        
        public static string HookPage_Text {
            get {
                return ResourceManager.GetString("HookPage.Text", resourceCulture);
            }
        }
        
        public static string HookPage_Console {
            get {
                return ResourceManager.GetString("HookPage.Console", resourceCulture);
            }
        }
        
        public static string HookPage_SelectText {
            get {
                return ResourceManager.GetString("HookPage.SelectText", resourceCulture);
            }
        }
        
        public static string HookPage_Submit {
            get {
                return ResourceManager.GetString("HookPage.Submit", resourceCulture);
            }
        }
        
        public static string GameView_MaxLenthTip {
            get {
                return ResourceManager.GetString("GameView.MaxLenthTip", resourceCulture);
            }
        }
        
        public static string MeCabPage_JapaneseText {
            get {
                return ResourceManager.GetString("MeCabPage.JapaneseText", resourceCulture);
            }
        }
        
        public static string GeneralPage_AppendText {
            get {
                return ResourceManager.GetString("GeneralPage.AppendText", resourceCulture);
            }
        }
        
        public static string GeneralPage_Title {
            get {
                return ResourceManager.GetString("GeneralPage.Title", resourceCulture);
            }
        }
        
        public static string MeCabPage_Title {
            get {
                return ResourceManager.GetString("MeCabPage.Title", resourceCulture);
            }
        }
        
        public static string MeCabPage_PositionFormat {
            get {
                return ResourceManager.GetString("MeCabPage.PositionFormat", resourceCulture);
            }
        }
        
        public static string MeCabPage_FuriganaTop {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaTop", resourceCulture);
            }
        }
        
        public static string MeCabPage_FuriganaBottom {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaBottom", resourceCulture);
            }
        }
        
        public static string MeCabPage_TextVertical {
            get {
                return ResourceManager.GetString("MeCabPage.TextVertical", resourceCulture);
            }
        }
        
        public static string MeCabPage_FuriganaType {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaType", resourceCulture);
            }
        }
        
        public static string MeCabPage_Romaji {
            get {
                return ResourceManager.GetString("MeCabPage.Romaji", resourceCulture);
            }
        }
        
        public static string MeCabPage_Hiragana {
            get {
                return ResourceManager.GetString("MeCabPage.Hiragana", resourceCulture);
            }
        }
        
        public static string MeCabPage_Katakana {
            get {
                return ResourceManager.GetString("MeCabPage.Katakana", resourceCulture);
            }
        }
        
        public static string GameView_SwitchFullScreen {
            get {
                return ResourceManager.GetString("GameView.SwitchFullScreen", resourceCulture);
            }
        }
        
        public static string GameView_FocusTip {
            get {
                return ResourceManager.GetString("GameView.FocusTip", resourceCulture);
            }
        }
        
        public static string GameView_ActionCenter {
            get {
                return ResourceManager.GetString("GameView.ActionCenter", resourceCulture);
            }
        }
        
        public static string GameView_TaskView {
            get {
                return ResourceManager.GetString("GameView.TaskView", resourceCulture);
            }
        }
        
        public static string GameView_ScreenShot {
            get {
                return ResourceManager.GetString("GameView.ScreenShot", resourceCulture);
            }
        }
        
        public static string GameView_Preference {
            get {
                return ResourceManager.GetString("GameView.Preference", resourceCulture);
            }
        }
        
        public static string SelectProcess_ProcessExit {
            get {
                return ResourceManager.GetString("SelectProcess.ProcessExit", resourceCulture);
            }
        }
        
        public static string HookPage_SelectedTextInitTip {
            get {
                return ResourceManager.GetString("HookPage.SelectedTextInitTip", resourceCulture);
            }
        }
        
        public static string HookPage_Title {
            get {
                return ResourceManager.GetString("HookPage.Title", resourceCulture);
            }
        }
        
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        public static string MeCabPage_FuriganaDefault {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaDefault", resourceCulture);
            }
        }
        
        public static string GameView_SwitchWindow {
            get {
                return ResourceManager.GetString("GameView.SwitchWindow", resourceCulture);
            }
        }
        
        public static string HookPage_RegExpTag1 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag1", resourceCulture);
            }
        }
        
        public static string HookPage_RegExpTag2 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag2", resourceCulture);
            }
        }
        
        public static string HookPage_RegExpTag3 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag3", resourceCulture);
            }
        }
        
        public static string HookPage_RegExpTag4 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag4", resourceCulture);
            }
        }
        
        public static string HookPage_RegExpTag5 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag5", resourceCulture);
            }
        }
        
        public static string HookPage_RegExpTip {
            get {
                return ResourceManager.GetString("HookPage.RegExpTip", resourceCulture);
            }
        }
        
        public static string HookPage_TextThreadRefreshTip {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshTip", resourceCulture);
            }
        }
        
        public static string HookPage_CodeInsertDialogTip {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertDialogTip", resourceCulture);
            }
        }
        
        public static string HookPage_CodeInsertLabel {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertLabel", resourceCulture);
            }
        }
        
        public static string HookPage_TextThreadRefreshLabel {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshLabel", resourceCulture);
            }
        }
        
        public static string HookPage_CodeSearchTip {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchTip", resourceCulture);
            }
        }
        
        public static string HookPage_CodeSearchNoResult {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchNoResult", resourceCulture);
            }
        }
        
        public static string HookPage_CodeSearchCancel {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchCancel", resourceCulture);
            }
        }
        
        public static string GameView_FontDecreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontDecreaseTip", resourceCulture);
            }
        }
        
        public static string GameView_FontIncreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontIncreaseTip", resourceCulture);
            }
        }
        
        public static string GameView_VolumeIncreaseTip {
            get {
                return ResourceManager.GetString("GameView.VolumeIncreaseTip", resourceCulture);
            }
        }
        
        public static string GameView_VolumeDecreaseTip {
            get {
                return ResourceManager.GetString("GameView.VolumeDecreaseTip", resourceCulture);
            }
        }
        
        public static string GameView_PinnedTip {
            get {
                return ResourceManager.GetString("GameView.PinnedTip", resourceCulture);
            }
        }
        
        public static string GameView_UnpinTip {
            get {
                return ResourceManager.GetString("GameView.UnpinTip", resourceCulture);
            }
        }
        
        public static string GeneralPage_Misc {
            get {
                return ResourceManager.GetString("GeneralPage.Misc", resourceCulture);
            }
        }
        
        public static string GeneralPage_DeepL {
            get {
                return ResourceManager.GetString("GeneralPage.DeepL", resourceCulture);
            }
        }
        
        public static string GeneralPage_DeepLDownload {
            get {
                return ResourceManager.GetString("GeneralPage.DeepLDownload", resourceCulture);
            }
        }
        
        public static string GeneralPage_Brightness {
            get {
                return ResourceManager.GetString("GeneralPage.Brightness", resourceCulture);
            }
        }
        
        public static string GeneralPage_BrightnessTip {
            get {
                return ResourceManager.GetString("GeneralPage.BrightnessTip", resourceCulture);
            }
        }
        
        public static string MeCabPage_TextFlyout {
            get {
                return ResourceManager.GetString("MeCabPage.TextFlyout", resourceCulture);
            }
        }
        
        public static string MeCabPage_Dict {
            get {
                return ResourceManager.GetString("MeCabPage.Dict", resourceCulture);
            }
        }
        
        public static string CardControl_CloseTip {
            get {
                return ResourceManager.GetString("CardControl.CloseTip", resourceCulture);
            }
        }
        
        public static string CardControl_SelectTextTip {
            get {
                return ResourceManager.GetString("CardControl.SelectTextTip", resourceCulture);
            }
        }
        
        public static string Textractor_AlreadyInject {
            get {
                return ResourceManager.GetString("Textractor.AlreadyInject", resourceCulture);
            }
        }
        
        public static string Textractor_InvalidCode {
            get {
                return ResourceManager.GetString("Textractor.InvalidCode", resourceCulture);
            }
        }
        
        public static string Textractor_Init {
            get {
                return ResourceManager.GetString("Textractor.Init", resourceCulture);
            }
        }
        
        public static string Textractor_InjectFailed {
            get {
                return ResourceManager.GetString("Textractor.InjectFailed", resourceCulture);
            }
        }
        
        public static string Textractor_InvalidProcess {
            get {
                return ResourceManager.GetString("Textractor.InvalidProcess", resourceCulture);
            }
        }
        
        public static string Textractor_Clipboard {
            get {
                return ResourceManager.GetString("Textractor.Clipboard", resourceCulture);
            }
        }
        
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        public static string HookPage_RCodeLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeLabel", resourceCulture);
            }
        }
        
        public static string HookPage_RCodeTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTip", resourceCulture);
            }
        }
        
        public static string GameViewModel_TextWaitingMessage {
            get {
                return ResourceManager.GetString("GameViewModel.TextWaitingMessage", resourceCulture);
            }
        }
        
        public static string GameView_ResetTouchPos {
            get {
                return ResourceManager.GetString("GameView.ResetTouchPos", resourceCulture);
            }
        }
        
        public static string GameView_TouchToMouse {
            get {
                return ResourceManager.GetString("GameView.TouchToMouse", resourceCulture);
            }
        }
        
        public static string GeneralPage_OutsideWindow {
            get {
                return ResourceManager.GetString("GeneralPage.OutsideWindow", resourceCulture);
            }
        }
        
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common.Close", resourceCulture);
            }
        }
        
        public static string HookPage_RCodeSearch {
            get {
                return ResourceManager.GetString("HookPage.RCodeSearch", resourceCulture);
            }
        }
        
        public static string HookPage_RCodeInputLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeInputLabel", resourceCulture);
            }
        }
        
        public static string HookPage_RCodeClipTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeClipTip", resourceCulture);
            }
        }
        
        public static string HookPage_RCodeTextValidationTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTextValidationTip", resourceCulture);
            }
        }
        
        public static string HookPage_SubmitDialogMessage {
            get {
                return ResourceManager.GetString("HookPage.SubmitDialogMessage", resourceCulture);
            }
        }
        
        public static string MeCabPage_SelectDict {
            get {
                return ResourceManager.GetString("MeCabPage.SelectDict", resourceCulture);
            }
        }
        
        public static string MeCabPage_SelectDictTip {
            get {
                return ResourceManager.GetString("MeCabPage.SelectDictTip", resourceCulture);
            }
        }
        
        public static string SelectProcess_ProcessItself {
            get {
                return ResourceManager.GetString("SelectProcess_ProcessItself", resourceCulture);
            }
        }
        
        public static string Translator_BaiduWeb {
            get {
                return ResourceManager.GetString("Translator.BaiduWeb", resourceCulture);
            }
        }
        
        public static string Translator_BaiduApi {
            get {
                return ResourceManager.GetString("Translator.BaiduApi", resourceCulture);
            }
        }
        
        public static string Translator_Caiyun {
            get {
                return ResourceManager.GetString("Translator.Caiyun", resourceCulture);
            }
        }
        
        public static string Translator_NiuTrans {
            get {
                return ResourceManager.GetString("Translator.NiuTrans", resourceCulture);
            }
        }
        
        public static string Translator_TencentMt {
            get {
                return ResourceManager.GetString("Translator.TencentMt", resourceCulture);
            }
        }
        
        public static string Translator_Yeekit {
            get {
                return ResourceManager.GetString("Translator.Yeekit", resourceCulture);
            }
        }
        
        public static string Translator_Youdao {
            get {
                return ResourceManager.GetString("Translator.Youdao", resourceCulture);
            }
        }
        
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        public static string Translator_GoogleCn {
            get {
                return ResourceManager.GetString("Translator.GoogleCn", resourceCulture);
            }
        }
        
        public static string Common_Test {
            get {
                return ResourceManager.GetString("Common.Test", resourceCulture);
            }
        }
        
        public static string Common_RestoreDefault {
            get {
                return ResourceManager.GetString("Common.RestoreDefault", resourceCulture);
            }
        }
        
        public static string TransPage_Title {
            get {
                return ResourceManager.GetString("TransPage.Title", resourceCulture);
            }
        }
        
        public static string TransPage_TransLabel {
            get {
                return ResourceManager.GetString("TransPage.TransLabel", resourceCulture);
            }
        }
        
        public static string TransPage_To {
            get {
                return ResourceManager.GetString("TransPage.To", resourceCulture);
            }
        }
        
        public static string TransPage_TranslatorDetail {
            get {
                return ResourceManager.GetString("TransPage.TranslatorDetail", resourceCulture);
            }
        }
        
        public static string Common_Warn {
            get {
                return ResourceManager.GetString("Common.Warn", resourceCulture);
            }
        }
        
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        public static string Installer_DeleteTip {
            get {
                return ResourceManager.GetString("Installer.DeleteTip", resourceCulture);
            }
        }
        
        public static string Installer_DeleteCheckBox {
            get {
                return ResourceManager.GetString("Installer.DeleteCheckBox", resourceCulture);
            }
        }
        
        public static string GeneralPage_CacheSpaceLabel {
            get {
                return ResourceManager.GetString("GeneralPage.CacheSpaceLabel", resourceCulture);
            }
        }
        
        public static string SelectProcess_NoIconProc {
            get {
                return ResourceManager.GetString("SelectProcess.NoIconProc", resourceCulture);
            }
        }
        
        public static string OokiiDialog_ClipboardLabel {
            get {
                return ResourceManager.GetString("OokiiDialog.ClipboardLabel", resourceCulture);
            }
        }
        
        public static string ErrorDialog_Content {
            get {
                return ResourceManager.GetString("ErrorDialog.Content", resourceCulture);
            }
        }
        
        public static string Installer_Title {
            get {
                return ResourceManager.GetString("Installer.Title", resourceCulture);
            }
        }
        
        public static string SelectProcess_AdminTip {
            get {
                return ResourceManager.GetString("SelectProcess.AdminTip", resourceCulture);
            }
        }
        
        public static string SelectProcess_EhNotExist {
            get {
                return ResourceManager.GetString("SelectProcess.EhNotExist", resourceCulture);
            }
        }
        
        public static string SelectProcess_CheckPath {
            get {
                return ResourceManager.GetString("SelectProcess.CheckPath", resourceCulture);
            }
        }
        
        public static string App_ErrorDialog {
            get {
                return ResourceManager.GetString("App.ErrorDialog", resourceCulture);
            }
        }
        
        public static string App_ErrorDialogExInfo {
            get {
                return ResourceManager.GetString("App.ErrorDialogExInfo", resourceCulture);
            }
        }
        
        public static string App_StartNoParameter {
            get {
                return ResourceManager.GetString("App.StartNoParameter", resourceCulture);
            }
        }
        
        public static string App_StartItself {
            get {
                return ResourceManager.GetString("App.StartItself", resourceCulture);
            }
        }
        
        public static string GeneralPage_ButtonBiggerSize {
            get {
                return ResourceManager.GetString("GeneralPage.ButtonBiggerSize", resourceCulture);
            }
        }
        
        public static string GeneralPage_AssistiveTouch {
            get {
                return ResourceManager.GetString("GeneralPage.AssistiveTouch", resourceCulture);
            }
        }
        
        public static string GeneralPage_DpiCompatibility {
            get {
                return ResourceManager.GetString("GeneralPage.DpiCompatibility", resourceCulture);
            }
        }
        
        public static string GeneralPage_FalseTouchMask {
            get {
                return ResourceManager.GetString("GeneralPage.FalseTouchMask", resourceCulture);
            }
        }
        
        public static string GameView_TouchKeyboard {
            get {
                return ResourceManager.GetString("GameView.TouchKeyboard", resourceCulture);
            }
        }
        
        public static string GameView_Functions {
            get {
                return ResourceManager.GetString("GameView.Functions", resourceCulture);
            }
        }
        
        public static string GameView_VirtualKeyboard {
            get {
                return ResourceManager.GetString("GameView.VirtualKeyboard", resourceCulture);
            }
        }
        
        public static string About_Update_CloseGameTip {
            get {
                return ResourceManager.GetString("About.Update.CloseGameTip", resourceCulture);
            }
        }
        
        public static string About_Update_Tip {
            get {
                return ResourceManager.GetString("About.Update.Tip", resourceCulture);
            }
        }
        
        public static string About_Update_PreviewWarning {
            get {
                return ResourceManager.GetString("About.Update.PreviewWarning", resourceCulture);
            }
        }
        
        public static string About_CheckingVersion {
            get {
                return ResourceManager.GetString("About.CheckingVersion", resourceCulture);
            }
        }
        
        public static string About_NewVersion {
            get {
                return ResourceManager.GetString("About.NewVersion", resourceCulture);
            }
        }
        
        public static string About_LatestVersion {
            get {
                return ResourceManager.GetString("About.LatestVersion", resourceCulture);
            }
        }
        
        public static string About_PreviewLatestVersion {
            get {
                return ResourceManager.GetString("About.PreviewLatestVersion", resourceCulture);
            }
        }
        
        public static string About_CheckingFailed {
            get {
                return ResourceManager.GetString("About.CheckingFailed", resourceCulture);
            }
        }
        
        public static string About_PreviewVersion {
            get {
                return ResourceManager.GetString("About.PreviewVersion", resourceCulture);
            }
        }
        
        public static string About_NightlyBuild {
            get {
                return ResourceManager.GetString("About.NightlyBuild", resourceCulture);
            }
        }
        
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common.Update", resourceCulture);
            }
        }
    }
}
