//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeHelper.Common.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErogeHelper.Common.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Connect to Github failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_CheckingFailed {
            get {
                return ResourceManager.GetString("About.CheckingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking update ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_CheckingVersion {
            get {
                return ResourceManager.GetString("About.CheckingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contributors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Contributors {
            get {
                return ResourceManager.GetString("About.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dependencies に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Dependencies {
            get {
                return ResourceManager.GetString("About.Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you find any bugs, please open a new issue in the github repository. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_FileABug {
            get {
                return ResourceManager.GetString("About.FileABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub repository に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About.GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_LatestVersion {
            get {
                return ResourceManager.GetString("About.LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found new version {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_NewVersion {
            get {
                return ResourceManager.GetString("About.NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Pre-Release version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_NightlyBuild {
            get {
                return ResourceManager.GetString("About.NightlyBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open a new issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_OpenNewIssue {
            get {
                return ResourceManager.GetString("About.OpenNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest preview version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_PreviewLatestVersion {
            get {
                return ResourceManager.GetString("About.PreviewLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_PreviewVersion {
            get {
                return ResourceManager.GetString("About.PreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please save and close your game in purpose to finish the update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Update_CloseGameTip {
            get {
                return ResourceManager.GetString("About.Update.CloseGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///NOTE: You are about updating to dev version. This version may not stable only suit for advance users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Update_PreviewWarning {
            get {
                return ResourceManager.GetString("About.Update.PreviewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is new version {0} available. Do you want to update the application now? (if it said Locate Emulator is in using, Please close the game, then click try again) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Update_Tip {
            get {
                return ResourceManager.GetString("About.Update.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErogeHelper v{0} - {1} Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_ErrorDialog {
            get {
                return ResourceManager.GetString("App.ErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OS Version: {0}
        ///Caused by source `{1}`
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_ErrorDialogExInfo {
            get {
                return ResourceManager.GetString("App.ErrorDialogExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid game path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_StartInvalidPath {
            get {
                return ResourceManager.GetString("App.StartInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t open ErogeHelper itself に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_StartItself {
            get {
                return ResourceManager.GetString("App.StartItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t open ErogeHelper directly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_StartNoParameter {
            get {
                return ResourceManager.GetString("App.StartNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_ActionCenter {
            get {
                return ResourceManager.GetString("AssistiveTouch.ActionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_BrightnessDown {
            get {
                return ResourceManager.GetString("AssistiveTouch.BrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_BrightnessUp {
            get {
                return ResourceManager.GetString("AssistiveTouch.BrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseGame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_CloseGame {
            get {
                return ResourceManager.GetString("AssistiveTouch.CloseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_Device {
            get {
                return ResourceManager.GetString("AssistiveTouch.Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_FullScreen {
            get {
                return ResourceManager.GetString("AssistiveTouch.FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_Function {
            get {
                return ResourceManager.GetString("AssistiveTouch.Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_Game {
            get {
                return ResourceManager.GetString("AssistiveTouch.Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lose Focus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_LoseFocus {
            get {
                return ResourceManager.GetString("AssistiveTouch.LoseFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make eh not occupied focus when full-screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_LoseFocusTip {
            get {
                return ResourceManager.GetString("AssistiveTouch.LoseFocusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_Preference {
            get {
                return ResourceManager.GetString("AssistiveTouch.Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenShot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_ScreenShot {
            get {
                return ResourceManager.GetString("AssistiveTouch.ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_TaskView {
            get {
                return ResourceManager.GetString("AssistiveTouch.TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_TouchToMouse {
            get {
                return ResourceManager.GetString("AssistiveTouch.TouchToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a touch to mouse simulate layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_TouchToMouseTip {
            get {
                return ResourceManager.GetString("AssistiveTouch.TouchToMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_VirtualKeyboard {
            get {
                return ResourceManager.GetString("AssistiveTouch.VirtualKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_VolumeDecrease {
            get {
                return ResourceManager.GetString("AssistiveTouch.VolumeDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_VolumeIncrease {
            get {
                return ResourceManager.GetString("AssistiveTouch.VolumeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssistiveTouch_Window {
            get {
                return ResourceManager.GetString("AssistiveTouch.Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Card に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CardControl_CloseTip {
            get {
                return ResourceManager.GetString("CardControl.CloseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CardControl_SelectTextTip {
            get {
                return ResourceManager.GetString("CardControl.SelectTextTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Administrator {
            get {
                return ResourceManager.GetString("Common.Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_GetHelp {
            get {
                return ResourceManager.GetString("Common.GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_RestoreDefault {
            get {
                return ResourceManager.GetString("Common.RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Test {
            get {
                return ResourceManager.GetString("Common.Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Developing {
            get {
                return ResourceManager.GetString("Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErogeHelper run into some trouble. See error stack by click Detail information below. You can copy the message use Ctrl + C. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorDialog_Content {
            get {
                return ResourceManager.GetString("ErrorDialog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrease size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_FontDecreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontDecreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_FontIncreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontIncreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip too long text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_MaxLenthTip {
            get {
                return ResourceManager.GetString("GameView.MaxLenthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpin Japanese text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_PinnedTip {
            get {
                return ResourceManager.GetString("GameView.PinnedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try reset button position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_ResetTouchPos {
            get {
                return ResourceManager.GetString("GameView.ResetTouchPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Screen (Alt+Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_SwitchFullScreen {
            get {
                return ResourceManager.GetString("GameView.SwitchFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window (Alt + Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_SwitchWindow {
            get {
                return ResourceManager.GetString("GameView.SwitchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch keyboard keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_TouchKeyboard {
            get {
                return ResourceManager.GetString("GameView.TouchKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch to mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_TouchToMouse {
            get {
                return ResourceManager.GetString("GameView.TouchToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin Japanese text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameView_UnpinTip {
            get {
                return ResourceManager.GetString("GameView.UnpinTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for text... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameViewModel_TextWaitingMessage {
            get {
                return ResourceManager.GetString("GameViewModel.TextWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show other texts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_AppendText {
            get {
                return ResourceManager.GetString("GeneralPage.AppendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assistive Touch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_AssistiveTouch {
            get {
                return ResourceManager.GetString("GeneralPage.AssistiveTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_Brightness {
            get {
                return ResourceManager.GetString("GeneralPage.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would change the gamma value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_BrightnessTip {
            get {
                return ResourceManager.GetString("GeneralPage.BrightnessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White point size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_ButtonBiggerSize {
            get {
                return ResourceManager.GetString("GeneralPage.ButtonBiggerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cache files space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_CacheSpaceLabel {
            get {
                return ResourceManager.GetString("GeneralPage.CacheSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_CurrentGame {
            get {
                return ResourceManager.GetString("GeneralPage.CurrentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeepL client extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_DeepL {
            get {
                return ResourceManager.GetString("GeneralPage.DeepL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download DeepL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_DeepLDownload {
            get {
                return ResourceManager.GetString("GeneralPage.DeepLDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set DPI compatibility to &apos;Application&apos; automatically when starting game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_DpiCompatibility {
            get {
                return ResourceManager.GetString("GeneralPage.DpiCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prevent edge touches at the edge of the game when fullscreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_FalseTouchMask {
            get {
                return ResourceManager.GetString("GeneralPage.FalseTouchMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t display text window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_HideTextWindow {
            get {
                return ResourceManager.GetString("GeneralPage.HideTextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MISC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_Misc {
            get {
                return ResourceManager.GetString("GeneralPage.Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not inject process when startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_NotInjectStartup {
            get {
                return ResourceManager.GetString("GeneralPage.NotInjectStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use outside text window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_OutsideWindow {
            get {
                return ResourceManager.GetString("GeneralPage.OutsideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralPage_Title {
            get {
                return ResourceManager.GetString("GeneralPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eroge Helper - Hook Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookConfig_Title {
            get {
                return ResourceManager.GetString("HookConfig.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_Clipboard {
            get {
                return ResourceManager.GetString("HookPage.Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle this to add clipboard monitor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_ClipboardTip {
            get {
                return ResourceManager.GetString("HookPage.ClipboardTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input HCode or RCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_CodeInsertDialogTip {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertDialogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_CodeInsertLabel {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_CodeSearchCancel {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_CodeSearchNoResult {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search code on Aniclan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_CodeSearchTip {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_Console {
            get {
                return ResourceManager.GetString("HookPage.Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid h-code format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_HCodeInvalidFormat {
            get {
                return ResourceManager.GetString("HookPage.HCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hook Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_HookCode {
            get {
                return ResourceManager.GetString("HookPage.HookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current in use hook:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_HookNameLabel {
            get {
                return ResourceManager.GetString("HookPage.HookNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_Insert {
            get {
                return ResourceManager.GetString("HookPage.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid regular expressions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_InvalidRegExp {
            get {
                return ResourceManager.GetString("HookPage.InvalidRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.google.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_LinkSetHook {
            get {
                return ResourceManager.GetString("HookPage.LinkSetHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.google.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_LinkWhatIsHook {
            get {
                return ResourceManager.GetString("HookPage.LinkWhatIsHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select text area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RCodeClipTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeClipTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the current text displayed by the game and type from the beginning of the text.
        ///(Including the &apos;「&apos;　symbol, if exist)
        ///(Read-Code only work this turn during the game run) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RCodeInputLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RCodeLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RCodeSearch {
            get {
                return ResourceManager.GetString("HookPage.RCodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text should more than 5 characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RCodeTextValidationTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTextValidationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search text help find out read code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RCodeTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expressions (Optional) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExp {
            get {
                return ResourceManager.GetString("HookPage.RegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters before &apos;「&apos; or &apos;『&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExpTag1 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters after &apos;」&apos; or &apos;』&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExpTag2 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ruby like &lt;.*?&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExpTag3 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linebreaks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExpTag4 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any Ascii charactors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExpTag5 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick up a RegExp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RegExpTip {
            get {
                return ResourceManager.GetString("HookPage.RegExpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inject the game again に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_ReInject {
            get {
                return ResourceManager.GetString("HookPage.ReInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ReiPatcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_ReiPatcher {
            get {
                return ResourceManager.GetString("HookPage.ReiPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove hook に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_RemoveHook {
            get {
                return ResourceManager.GetString("HookPage.RemoveHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_SelectedText {
            get {
                return ResourceManager.GetString("HookPage.SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slide down to select a text thread に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_SelectedTextInitTip {
            get {
                return ResourceManager.GetString("HookPage.SelectedTextInitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_SelectText {
            get {
                return ResourceManager.GetString("HookPage.SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to set hook? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_SetHook {
            get {
                return ResourceManager.GetString("HookPage.SetHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_Submit {
            get {
                return ResourceManager.GetString("HookPage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update succeed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_SubmitDialogMessage {
            get {
                return ResourceManager.GetString("HookPage.SubmitDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_Text {
            get {
                return ResourceManager.GetString("HookPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Clean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_TextClean {
            get {
                return ResourceManager.GetString("HookPage.TextClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Cleaning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_TextCleaning {
            get {
                return ResourceManager.GetString("HookPage.TextCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_TextThreadRefreshLabel {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh current text thread に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_TextThreadRefreshTip {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hook Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_Title {
            get {
                return ResourceManager.GetString("HookPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unity game can&apos;t inject automatically に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_UnityGameTip {
            get {
                return ResourceManager.GetString("HookPage.UnityGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is Hook Code? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookPage_WhatIsHook {
            get {
                return ResourceManager.GetString("HookPage.WhatIsHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookThreadItem_Character {
            get {
                return ResourceManager.GetString("HookThreadItem.Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HookThreadItem_Text {
            get {
                return ResourceManager.GetString("HookThreadItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Also delete EH cache files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installer_DeleteCheckBox {
            get {
                return ResourceManager.GetString("Installer.DeleteCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will delete all cache files such like config, subtitles, Mecab dictionary, game info database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installer_DeleteTip {
            get {
                return ResourceManager.GetString("Installer.DeleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will register Eroge Helper to the window context menu for &quot;.exe&quot; suffix programs. Please uninstall me before move or delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installer_Info {
            get {
                return ResourceManager.GetString("Installer.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installer_Register {
            get {
                return ResourceManager.GetString("Installer.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installer_Title {
            get {
                return ResourceManager.GetString("Installer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Installer_Unload {
            get {
                return ResourceManager.GetString("Installer.Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dict に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_Dict {
            get {
                return ResourceManager.GetString("MeCabPage.Dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FuriganaBottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_FuriganaBottom {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeCabPage.FuriganaDefault に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_FuriganaDefault {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaCabPage.FuriganaTop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_FuriganaTop {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Furigana display type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_FuriganaType {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiragana に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_Hiragana {
            get {
                return ResourceManager.GetString("MeCabPage.Hiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Japanese in text window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_JapaneseText {
            get {
                return ResourceManager.GetString("MeCabPage.JapaneseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katakana に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_Katakana {
            get {
                return ResourceManager.GetString("MeCabPage.Katakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text dispaly position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_PositionFormat {
            get {
                return ResourceManager.GetString("MeCabPage.PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Romaji に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_Romaji {
            get {
                return ResourceManager.GetString("MeCabPage.Romaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose file UniDic.eh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_SelectDict {
            get {
                return ResourceManager.GetString("MeCabPage.SelectDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack UniDic.eh to enable this function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_SelectDictTip {
            get {
                return ResourceManager.GetString("MeCabPage.SelectDictTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Flyout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_TextFlyout {
            get {
                return ResourceManager.GetString("MeCabPage.TextFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeCabPage.TextVertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_TextVertical {
            get {
                return ResourceManager.GetString("MeCabPage.TextVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeCab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeCabPage_Title {
            get {
                return ResourceManager.GetString("MeCabPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note lose focus only recommend when you can not interact with eh when full-screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBox_LoseFocusWarn {
            get {
                return ResourceManager.GetString("MessageBox.LoseFocusWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout! Game window not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBox_TimeoutInfo {
            get {
                return ResourceManager.GetString("MessageBox.TimeoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm and copy error to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OokiiDialog_ClipboardLabel {
            get {
                return ResourceManager.GetString("OokiiDialog.ClipboardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Undone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReiPatcherDialog_Error {
            get {
                return ResourceManager.GetString("ReiPatcherDialog.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   √ Finish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReiPatcherDialog_OK {
            get {
                return ResourceManager.GetString("ReiPatcherDialog.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⭕ May need restart game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReiPatcherDialog_Tip {
            get {
                return ResourceManager.GetString("ReiPatcherDialog.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the right game? Try restart ErogeHelper.ProcessSelector.exe in Administrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_AdminTip {
            get {
                return ResourceManager.GetString("SelectProcess.AdminTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Check path  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_CheckPath {
            get {
                return ResourceManager.GetString("SelectProcess.CheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not found the ErogeHelper.exe main executable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_EHNotExist {
            get {
                return ResourceManager.GetString("SelectProcess.EHNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_InjectButton {
            get {
                return ResourceManager.GetString("SelectProcess.InjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_Label {
            get {
                return ResourceManager.GetString("SelectProcess.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include no icon program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_NoIconProc {
            get {
                return ResourceManager.GetString("SelectProcess.NoIconProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process has gone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_ProcessExit {
            get {
                return ResourceManager.GetString("SelectProcess.ProcessExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot choose EH itself~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_ProcessItself {
            get {
                return ResourceManager.GetString("SelectProcess_ProcessItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can also use ErogeHelper.Installer.exe to install me~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_Tips {
            get {
                return ResourceManager.GetString("SelectProcess.Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcess_Title {
            get {
                return ResourceManager.GetString("SelectProcess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Textractor: already injected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Textractor_AlreadyInject {
            get {
                return ResourceManager.GetString("Textractor.AlreadyInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Textractor_Clipboard {
            get {
                return ResourceManager.GetString("Textractor.Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Textractor: initialization completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Textractor_Init {
            get {
                return ResourceManager.GetString("Textractor.Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Textractor: couldn&apos;t inject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Textractor_InjectFailed {
            get {
                return ResourceManager.GetString("Textractor.InjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Textractor: invalid code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Textractor_InvalidCode {
            get {
                return ResourceManager.GetString("Textractor.InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Textractor: invalid process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Textractor_InvalidProcess {
            get {
                return ResourceManager.GetString("Textractor.InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   👈Drag the square に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextWindow_DragAreaTip {
            get {
                return ResourceManager.GetString("TextWindow.DragAreaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tip: Has not enable Japanese text or any translator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextWindow_EnableFunctionTip {
            get {
                return ResourceManager.GetString("TextWindow.EnableFunctionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Important: Seems like hasn&apos;t set hook yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextWindow_SetHookTip {
            get {
                return ResourceManager.GetString("TextWindow.SetHookTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for text... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextWindow_WaitingForText {
            get {
                return ResourceManager.GetString("TextWindow.WaitingForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BaiduApi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_BaiduApi {
            get {
                return ResourceManager.GetString("Translator.BaiduApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BaiduWeb に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_BaiduWeb {
            get {
                return ResourceManager.GetString("Translator.BaiduWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caiyun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_Caiyun {
            get {
                return ResourceManager.GetString("Translator.Caiyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google Translate (CN) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_GoogleCn {
            get {
                return ResourceManager.GetString("Translator.GoogleCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NiuTrans に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_NiuTrans {
            get {
                return ResourceManager.GetString("Translator.NiuTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TencentMt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_TencentMt {
            get {
                return ResourceManager.GetString("Translator.TencentMt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeekit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_Yeekit {
            get {
                return ResourceManager.GetString("Translator.Yeekit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Youdao に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Translator_Youdao {
            get {
                return ResourceManager.GetString("Translator.Youdao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AIUEO song に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_Aiueo {
            get {
                return ResourceManager.GetString("TransPage.Aiueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.youtube.com/watch?v=LrXHizFaol0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_AiueoLink {
            get {
                return ResourceManager.GetString("TransPage.AiueoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Know some Japanese alphabet can help better understanding! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_LearnJapaneseTip {
            get {
                return ResourceManager.GetString("TransPage.LearnJapaneseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tae Kim&apos;s Guide to Learning Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_TaeKimGrammer {
            get {
                return ResourceManager.GetString("TransPage.TaeKimGrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://guidetojapanese.org/learn/grammar/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_TaeKimGrammerLink {
            get {
                return ResourceManager.GetString("TransPage.TaeKimGrammerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machine Translation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_Title {
            get {
                return ResourceManager.GetString("TransPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_To {
            get {
                return ResourceManager.GetString("TransPage.To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_TransLabel {
            get {
                return ResourceManager.GetString("TransPage.TransLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransPage_TranslatorDetail {
            get {
                return ResourceManager.GetString("TransPage.TranslatorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to Speech に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TTSPage_Title {
            get {
                return ResourceManager.GetString("TTSPage.Title", resourceCulture);
            }
        }
    }
}
