//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErogeHelper.Shared.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErogeHelper.Shared.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 No Internet or proxy failed 的本地化字符串。
        /// </summary>
        public static string About_CheckingFailed {
            get {
                return ResourceManager.GetString("About.CheckingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking update ... 的本地化字符串。
        /// </summary>
        public static string About_CheckingVersion {
            get {
                return ResourceManager.GetString("About.CheckingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contributors 的本地化字符串。
        /// </summary>
        public static string About_Contributors {
            get {
                return ResourceManager.GetString("About.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependencies 的本地化字符串。
        /// </summary>
        public static string About_Dependencies {
            get {
                return ResourceManager.GetString("About.Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you find any bugs, please open a new issue in the github repository. 的本地化字符串。
        /// </summary>
        public static string About_FileABug {
            get {
                return ResourceManager.GetString("About.FileABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub repository 的本地化字符串。
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About.GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest version 的本地化字符串。
        /// </summary>
        public static string About_LatestVersion {
            get {
                return ResourceManager.GetString("About.LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found new version {0} 的本地化字符串。
        /// </summary>
        public static string About_NewVersion {
            get {
                return ResourceManager.GetString("About.NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Pre-Release version 的本地化字符串。
        /// </summary>
        public static string About_NightlyBuild {
            get {
                return ResourceManager.GetString("About.NightlyBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a new issue 的本地化字符串。
        /// </summary>
        public static string About_OpenNewIssue {
            get {
                return ResourceManager.GetString("About.OpenNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest preview version 的本地化字符串。
        /// </summary>
        public static string About_PreviewLatestVersion {
            get {
                return ResourceManager.GetString("About.PreviewLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview version 的本地化字符串。
        /// </summary>
        public static string About_PreviewVersion {
            get {
                return ResourceManager.GetString("About.PreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please save and close your game in purpose to finish the update 的本地化字符串。
        /// </summary>
        public static string About_Update_CloseGameTip {
            get {
                return ResourceManager.GetString("About.Update.CloseGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///NOTE: You are about updating to dev version. This version may not stable only suit for advance users 的本地化字符串。
        /// </summary>
        public static string About_Update_PreviewWarning {
            get {
                return ResourceManager.GetString("About.Update.PreviewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is new version {0} available. Do you want to update the application now? (if it said Locate Emulator is in using, Please close the game, then click try again) 的本地化字符串。
        /// </summary>
        public static string About_Update_Tip {
            get {
                return ResourceManager.GetString("About.Update.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version :  的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ErogeHelper v{0} - {1} Error 的本地化字符串。
        /// </summary>
        public static string App_ErrorDialog {
            get {
                return ResourceManager.GetString("App.ErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Version: {0}
        ///Caused by source `{1}`
        /// 的本地化字符串。
        /// </summary>
        public static string App_ErrorDialogExInfo {
            get {
                return ResourceManager.GetString("App.ErrorDialogExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not run ErogeHelper itself 的本地化字符串。
        /// </summary>
        public static string App_StartItself {
            get {
                return ResourceManager.GetString("App.StartItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not run ErogeHelper directly 的本地化字符串。
        /// </summary>
        public static string App_StartNoParameter {
            get {
                return ResourceManager.GetString("App.StartNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Center 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_ActionCenter {
            get {
                return ResourceManager.GetString("AssistiveTouch.ActionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness Down 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_BrightnessDown {
            get {
                return ResourceManager.GetString("AssistiveTouch.BrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness Up 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_BrightnessUp {
            get {
                return ResourceManager.GetString("AssistiveTouch.BrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloseGame 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_CloseGame {
            get {
                return ResourceManager.GetString("AssistiveTouch.CloseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_Device {
            get {
                return ResourceManager.GetString("AssistiveTouch.Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_FullScreen {
            get {
                return ResourceManager.GetString("AssistiveTouch.FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_Function {
            get {
                return ResourceManager.GetString("AssistiveTouch.Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_Game {
            get {
                return ResourceManager.GetString("AssistiveTouch.Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lose Focus 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_LoseFocus {
            get {
                return ResourceManager.GetString("AssistiveTouch.LoseFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make eh not occupied focus when full-screen 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_LoseFocusTip {
            get {
                return ResourceManager.GetString("AssistiveTouch.LoseFocusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note lose focus only recommend when you can not interact with eh when full-screen. 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_LoseFocusWarn {
            get {
                return ResourceManager.GetString("AssistiveTouch.LoseFocusWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_Preference {
            get {
                return ResourceManager.GetString("AssistiveTouch.Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenShot 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_ScreenShot {
            get {
                return ResourceManager.GetString("AssistiveTouch.ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task View 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_TaskView {
            get {
                return ResourceManager.GetString("AssistiveTouch.TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Mouse 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_TouchToMouse {
            get {
                return ResourceManager.GetString("AssistiveTouch.TouchToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a touch to mouse simulate layer 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_TouchToMouseTip {
            get {
                return ResourceManager.GetString("AssistiveTouch.TouchToMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_VirtualKeyboard {
            get {
                return ResourceManager.GetString("AssistiveTouch.VirtualKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Down 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_VolumeDecrease {
            get {
                return ResourceManager.GetString("AssistiveTouch.VolumeDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Up 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_VolumeIncrease {
            get {
                return ResourceManager.GetString("AssistiveTouch.VolumeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        public static string AssistiveTouch_Window {
            get {
                return ResourceManager.GetString("AssistiveTouch.Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Card 的本地化字符串。
        /// </summary>
        public static string CardControl_CloseTip {
            get {
                return ResourceManager.GetString("CardControl.CloseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select text 的本地化字符串。
        /// </summary>
        public static string CardControl_SelectTextTip {
            get {
                return ResourceManager.GetString("CardControl.SelectTextTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get help 的本地化字符串。
        /// </summary>
        public static string Common_GetHelp {
            get {
                return ResourceManager.GetString("Common.GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore default 的本地化字符串。
        /// </summary>
        public static string Common_RestoreDefault {
            get {
                return ResourceManager.GetString("Common.RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string Common_Test {
            get {
                return ResourceManager.GetString("Common.Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developing... 的本地化字符串。
        /// </summary>
        public static string Developing {
            get {
                return ResourceManager.GetString("Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ErogeHelper run into some trouble. See error stack by click Detail information below. You can copy the message use Ctrl + C. 的本地化字符串。
        /// </summary>
        public static string ErrorDialog_Content {
            get {
                return ResourceManager.GetString("ErrorDialog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrease size 的本地化字符串。
        /// </summary>
        public static string GameView_FontDecreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontDecreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase size 的本地化字符串。
        /// </summary>
        public static string GameView_FontIncreaseTip {
            get {
                return ResourceManager.GetString("GameView.FontIncreaseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip too long text 的本地化字符串。
        /// </summary>
        public static string GameView_MaxLenthTip {
            get {
                return ResourceManager.GetString("GameView.MaxLenthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpin Japanese text 的本地化字符串。
        /// </summary>
        public static string GameView_PinnedTip {
            get {
                return ResourceManager.GetString("GameView.PinnedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try reset button position 的本地化字符串。
        /// </summary>
        public static string GameView_ResetTouchPos {
            get {
                return ResourceManager.GetString("GameView.ResetTouchPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen (Alt+Enter) 的本地化字符串。
        /// </summary>
        public static string GameView_SwitchFullScreen {
            get {
                return ResourceManager.GetString("GameView.SwitchFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window (Alt + Enter) 的本地化字符串。
        /// </summary>
        public static string GameView_SwitchWindow {
            get {
                return ResourceManager.GetString("GameView.SwitchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touch keyboard keys 的本地化字符串。
        /// </summary>
        public static string GameView_TouchKeyboard {
            get {
                return ResourceManager.GetString("GameView.TouchKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touch to mouse 的本地化字符串。
        /// </summary>
        public static string GameView_TouchToMouse {
            get {
                return ResourceManager.GetString("GameView.TouchToMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Japanese text 的本地化字符串。
        /// </summary>
        public static string GameView_UnpinTip {
            get {
                return ResourceManager.GetString("GameView.UnpinTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for text... 的本地化字符串。
        /// </summary>
        public static string GameViewModel_TextWaitingMessage {
            get {
                return ResourceManager.GetString("GameViewModel.TextWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show other texts 的本地化字符串。
        /// </summary>
        public static string GeneralPage_AppendText {
            get {
                return ResourceManager.GetString("GeneralPage.AppendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assistive Touch 的本地化字符串。
        /// </summary>
        public static string GeneralPage_AssistiveTouch {
            get {
                return ResourceManager.GetString("GeneralPage.AssistiveTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness 的本地化字符串。
        /// </summary>
        public static string GeneralPage_Brightness {
            get {
                return ResourceManager.GetString("GeneralPage.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would change the gamma value 的本地化字符串。
        /// </summary>
        public static string GeneralPage_BrightnessTip {
            get {
                return ResourceManager.GetString("GeneralPage.BrightnessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button Bigger Size 的本地化字符串。
        /// </summary>
        public static string GeneralPage_ButtonBiggerSize {
            get {
                return ResourceManager.GetString("GeneralPage.ButtonBiggerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache files space 的本地化字符串。
        /// </summary>
        public static string GeneralPage_CacheSpaceLabel {
            get {
                return ResourceManager.GetString("GeneralPage.CacheSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Game 的本地化字符串。
        /// </summary>
        public static string GeneralPage_CurrentGame {
            get {
                return ResourceManager.GetString("GeneralPage.CurrentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeepL Client Extension 的本地化字符串。
        /// </summary>
        public static string GeneralPage_DeepL {
            get {
                return ResourceManager.GetString("GeneralPage.DeepL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download DeepL 的本地化字符串。
        /// </summary>
        public static string GeneralPage_DeepLDownload {
            get {
                return ResourceManager.GetString("GeneralPage.DeepLDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set DPI compatibility to &apos;Application&apos; automatically when starting game 的本地化字符串。
        /// </summary>
        public static string GeneralPage_DpiCompatibility {
            get {
                return ResourceManager.GetString("GeneralPage.DpiCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use edge false touch mask 的本地化字符串。
        /// </summary>
        public static string GeneralPage_FalseTouchMask {
            get {
                return ResourceManager.GetString("GeneralPage.FalseTouchMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t display text window 的本地化字符串。
        /// </summary>
        public static string GeneralPage_HideTextWindow {
            get {
                return ResourceManager.GetString("GeneralPage.HideTextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MISC 的本地化字符串。
        /// </summary>
        public static string GeneralPage_Misc {
            get {
                return ResourceManager.GetString("GeneralPage.Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not inject process when startup 的本地化字符串。
        /// </summary>
        public static string GeneralPage_NotInjectStartup {
            get {
                return ResourceManager.GetString("GeneralPage.NotInjectStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use outside text window 的本地化字符串。
        /// </summary>
        public static string GeneralPage_OutsideWindow {
            get {
                return ResourceManager.GetString("GeneralPage.OutsideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string GeneralPage_Title {
            get {
                return ResourceManager.GetString("GeneralPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eroge Helper - Hook Config 的本地化字符串。
        /// </summary>
        public static string HookConfig_Title {
            get {
                return ResourceManager.GetString("HookConfig.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        public static string HookPage_Clipboard {
            get {
                return ResourceManager.GetString("HookPage.Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle this to add clipboard monitor 的本地化字符串。
        /// </summary>
        public static string HookPage_ClipboardTip {
            get {
                return ResourceManager.GetString("HookPage.ClipboardTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input HCode or RCode 的本地化字符串。
        /// </summary>
        public static string HookPage_CodeInsertDialogTip {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertDialogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string HookPage_CodeInsertLabel {
            get {
                return ResourceManager.GetString("HookPage.CodeInsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string HookPage_CodeSearchCancel {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Result 的本地化字符串。
        /// </summary>
        public static string HookPage_CodeSearchNoResult {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search code on Aniclan 的本地化字符串。
        /// </summary>
        public static string HookPage_CodeSearchTip {
            get {
                return ResourceManager.GetString("HookPage.CodeSearchTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console Output 的本地化字符串。
        /// </summary>
        public static string HookPage_Console {
            get {
                return ResourceManager.GetString("HookPage.Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid h-code format 的本地化字符串。
        /// </summary>
        public static string HookPage_HCodeInvalidFormat {
            get {
                return ResourceManager.GetString("HookPage.HCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook Code 的本地化字符串。
        /// </summary>
        public static string HookPage_HookCode {
            get {
                return ResourceManager.GetString("HookPage.HookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current use hook:  的本地化字符串。
        /// </summary>
        public static string HookPage_HookNameLabel {
            get {
                return ResourceManager.GetString("HookPage.HookNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string HookPage_Insert {
            get {
                return ResourceManager.GetString("HookPage.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid regular expressions. 的本地化字符串。
        /// </summary>
        public static string HookPage_InvalidRegExp {
            get {
                return ResourceManager.GetString("HookPage.InvalidRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.google.com 的本地化字符串。
        /// </summary>
        public static string HookPage_LinkSetHook {
            get {
                return ResourceManager.GetString("HookPage.LinkSetHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.google.com 的本地化字符串。
        /// </summary>
        public static string HookPage_LinkWhatIsHook {
            get {
                return ResourceManager.GetString("HookPage.LinkWhatIsHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select text area 的本地化字符串。
        /// </summary>
        public static string HookPage_RCodeClipTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeClipTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the current text displayed by the game and type from the beginning of the text.
        ///(Including the &apos;「&apos;　symbol, if exist)
        ///(Read-Code only work this turn during the game run) 的本地化字符串。
        /// </summary>
        public static string HookPage_RCodeInputLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Code 的本地化字符串。
        /// </summary>
        public static string HookPage_RCodeLabel {
            get {
                return ResourceManager.GetString("HookPage.RCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string HookPage_RCodeSearch {
            get {
                return ResourceManager.GetString("HookPage.RCodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The text should more than 5 characters 的本地化字符串。
        /// </summary>
        public static string HookPage_RCodeTextValidationTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTextValidationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search text help find out read code 的本地化字符串。
        /// </summary>
        public static string HookPage_RCodeTip {
            get {
                return ResourceManager.GetString("HookPage.RCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular Expressions 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExp {
            get {
                return ResourceManager.GetString("HookPage.RegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete characters before &apos;「&apos; or &apos;『&apos; 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExpTag1 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete characters after &apos;」&apos; or &apos;』&apos; 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExpTag2 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete ruby like &lt;.*?&gt; 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExpTag3 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete linebreaks 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExpTag4 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete any Ascii chractors 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExpTag5 {
            get {
                return ResourceManager.GetString("HookPage.RegExpTag5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick up a RegExp 的本地化字符串。
        /// </summary>
        public static string HookPage_RegExpTip {
            get {
                return ResourceManager.GetString("HookPage.RegExpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject the game again 的本地化字符串。
        /// </summary>
        public static string HookPage_ReInject {
            get {
                return ResourceManager.GetString("HookPage.ReInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReiPatcher 的本地化字符串。
        /// </summary>
        public static string HookPage_ReiPatcher {
            get {
                return ResourceManager.GetString("HookPage.ReiPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove hook 的本地化字符串。
        /// </summary>
        public static string HookPage_RemoveHook {
            get {
                return ResourceManager.GetString("HookPage.RemoveHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Text 的本地化字符串。
        /// </summary>
        public static string HookPage_SelectedText {
            get {
                return ResourceManager.GetString("HookPage.SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide down to select a text thread 的本地化字符串。
        /// </summary>
        public static string HookPage_SelectedTextInitTip {
            get {
                return ResourceManager.GetString("HookPage.SelectedTextInitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Text 的本地化字符串。
        /// </summary>
        public static string HookPage_SelectText {
            get {
                return ResourceManager.GetString("HookPage.SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How to set hook? 的本地化字符串。
        /// </summary>
        public static string HookPage_SetHook {
            get {
                return ResourceManager.GetString("HookPage.SetHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string HookPage_Submit {
            get {
                return ResourceManager.GetString("HookPage.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update succeed 的本地化字符串。
        /// </summary>
        public static string HookPage_SubmitDialogMessage {
            get {
                return ResourceManager.GetString("HookPage.SubmitDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current text 的本地化字符串。
        /// </summary>
        public static string HookPage_Text {
            get {
                return ResourceManager.GetString("HookPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Clean 的本地化字符串。
        /// </summary>
        public static string HookPage_TextClean {
            get {
                return ResourceManager.GetString("HookPage.TextClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Cleaning 的本地化字符串。
        /// </summary>
        public static string HookPage_TextCleaning {
            get {
                return ResourceManager.GetString("HookPage.TextCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string HookPage_TextThreadRefreshLabel {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh current text thread 的本地化字符串。
        /// </summary>
        public static string HookPage_TextThreadRefreshTip {
            get {
                return ResourceManager.GetString("HookPage.TextThreadRefreshTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook Config 的本地化字符串。
        /// </summary>
        public static string HookPage_Title {
            get {
                return ResourceManager.GetString("HookPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unity game can&apos;t inject automatically 的本地化字符串。
        /// </summary>
        public static string HookPage_UnityGameTip {
            get {
                return ResourceManager.GetString("HookPage.UnityGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What is Hook Code? 的本地化字符串。
        /// </summary>
        public static string HookPage_WhatIsHook {
            get {
                return ResourceManager.GetString("HookPage.WhatIsHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        public static string HookThreadItem_Character {
            get {
                return ResourceManager.GetString("HookThreadItem.Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string HookThreadItem_Text {
            get {
                return ResourceManager.GetString("HookThreadItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Also delete EH cache files. 的本地化字符串。
        /// </summary>
        public static string Installer_DeleteCheckBox {
            get {
                return ResourceManager.GetString("Installer.DeleteCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will delete all cache files such like config, subtitles, Mecab dictionary, game info database 的本地化字符串。
        /// </summary>
        public static string Installer_DeleteTip {
            get {
                return ResourceManager.GetString("Installer.DeleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will register Eroge Helper to the window context menu for &quot;.exe&quot; suffix programs. Please uninstall me before move or delete. 的本地化字符串。
        /// </summary>
        public static string Installer_Info {
            get {
                return ResourceManager.GetString("Installer.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string Installer_Register {
            get {
                return ResourceManager.GetString("Installer.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installer 的本地化字符串。
        /// </summary>
        public static string Installer_Title {
            get {
                return ResourceManager.GetString("Installer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unload 的本地化字符串。
        /// </summary>
        public static string Installer_Unload {
            get {
                return ResourceManager.GetString("Installer.Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dict 的本地化字符串。
        /// </summary>
        public static string MeCabPage_Dict {
            get {
                return ResourceManager.GetString("MeCabPage.Dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FuriganaBottom 的本地化字符串。
        /// </summary>
        public static string MeCabPage_FuriganaBottom {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MeCabPage.FuriganaDefault 的本地化字符串。
        /// </summary>
        public static string MeCabPage_FuriganaDefault {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaCabPage.FuriganaTop 的本地化字符串。
        /// </summary>
        public static string MeCabPage_FuriganaTop {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Furigana display type 的本地化字符串。
        /// </summary>
        public static string MeCabPage_FuriganaType {
            get {
                return ResourceManager.GetString("MeCabPage.FuriganaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hiragana 的本地化字符串。
        /// </summary>
        public static string MeCabPage_Hiragana {
            get {
                return ResourceManager.GetString("MeCabPage.Hiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Japanese in text window 的本地化字符串。
        /// </summary>
        public static string MeCabPage_JapaneseText {
            get {
                return ResourceManager.GetString("MeCabPage.JapaneseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Katakana 的本地化字符串。
        /// </summary>
        public static string MeCabPage_Katakana {
            get {
                return ResourceManager.GetString("MeCabPage.Katakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text dispaly position 的本地化字符串。
        /// </summary>
        public static string MeCabPage_PositionFormat {
            get {
                return ResourceManager.GetString("MeCabPage.PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Romaji 的本地化字符串。
        /// </summary>
        public static string MeCabPage_Romaji {
            get {
                return ResourceManager.GetString("MeCabPage.Romaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose file UniDic.eh 的本地化字符串。
        /// </summary>
        public static string MeCabPage_SelectDict {
            get {
                return ResourceManager.GetString("MeCabPage.SelectDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack UniDic.eh to enable this function 的本地化字符串。
        /// </summary>
        public static string MeCabPage_SelectDictTip {
            get {
                return ResourceManager.GetString("MeCabPage.SelectDictTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Flyout 的本地化字符串。
        /// </summary>
        public static string MeCabPage_TextFlyout {
            get {
                return ResourceManager.GetString("MeCabPage.TextFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MeCabPage.TextVertical 的本地化字符串。
        /// </summary>
        public static string MeCabPage_TextVertical {
            get {
                return ResourceManager.GetString("MeCabPage.TextVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MeCab 的本地化字符串。
        /// </summary>
        public static string MeCabPage_Title {
            get {
                return ResourceManager.GetString("MeCabPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout! Game window not found 的本地化字符串。
        /// </summary>
        public static string MessageBox_TimeoutInfo {
            get {
                return ResourceManager.GetString("MessageBox.TimeoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm and copy error to clipboard 的本地化字符串。
        /// </summary>
        public static string OokiiDialog_ClipboardLabel {
            get {
                return ResourceManager.GetString("OokiiDialog.ClipboardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Undone 的本地化字符串。
        /// </summary>
        public static string ReiPatcherDialog_Error {
            get {
                return ResourceManager.GetString("ReiPatcherDialog.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 √ Finish 的本地化字符串。
        /// </summary>
        public static string ReiPatcherDialog_OK {
            get {
                return ResourceManager.GetString("ReiPatcherDialog.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⭕ May need restart game 的本地化字符串。
        /// </summary>
        public static string ReiPatcherDialog_Tip {
            get {
                return ResourceManager.GetString("ReiPatcherDialog.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find the right game? Try restart ErogeHelper.ProcessSelector.exe in Administrator 的本地化字符串。
        /// </summary>
        public static string SelectProcess_AdminTip {
            get {
                return ResourceManager.GetString("SelectProcess.AdminTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Check path  的本地化字符串。
        /// </summary>
        public static string SelectProcess_CheckPath {
            get {
                return ResourceManager.GetString("SelectProcess.CheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found the ErogeHelper.exe main executable 的本地化字符串。
        /// </summary>
        public static string SelectProcess_EHNotExist {
            get {
                return ResourceManager.GetString("SelectProcess.EHNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject 的本地化字符串。
        /// </summary>
        public static string SelectProcess_InjectButton {
            get {
                return ResourceManager.GetString("SelectProcess.InjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Application 的本地化字符串。
        /// </summary>
        public static string SelectProcess_Label {
            get {
                return ResourceManager.GetString("SelectProcess.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include no icon program 的本地化字符串。
        /// </summary>
        public static string SelectProcess_NoIconProc {
            get {
                return ResourceManager.GetString("SelectProcess.NoIconProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process has gone 的本地化字符串。
        /// </summary>
        public static string SelectProcess_ProcessExit {
            get {
                return ResourceManager.GetString("SelectProcess.ProcessExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot choose EH itself~ 的本地化字符串。
        /// </summary>
        public static string SelectProcess_ProcessItself {
            get {
                return ResourceManager.GetString("SelectProcess_ProcessItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can also use ErogeHelper.Installer.exe to install me~ 的本地化字符串。
        /// </summary>
        public static string SelectProcess_Tips {
            get {
                return ResourceManager.GetString("SelectProcess.Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Process 的本地化字符串。
        /// </summary>
        public static string SelectProcess_Title {
            get {
                return ResourceManager.GetString("SelectProcess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textractor: already injected 的本地化字符串。
        /// </summary>
        public static string Textractor_AlreadyInject {
            get {
                return ResourceManager.GetString("Textractor.AlreadyInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        public static string Textractor_Clipboard {
            get {
                return ResourceManager.GetString("Textractor.Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textractor: initialization completed 的本地化字符串。
        /// </summary>
        public static string Textractor_Init {
            get {
                return ResourceManager.GetString("Textractor.Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textractor: couldn&apos;t inject 的本地化字符串。
        /// </summary>
        public static string Textractor_InjectFailed {
            get {
                return ResourceManager.GetString("Textractor.InjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textractor: invalid code 的本地化字符串。
        /// </summary>
        public static string Textractor_InvalidCode {
            get {
                return ResourceManager.GetString("Textractor.InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textractor: invalid process 的本地化字符串。
        /// </summary>
        public static string Textractor_InvalidProcess {
            get {
                return ResourceManager.GetString("Textractor.InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 👈Drag the square 的本地化字符串。
        /// </summary>
        public static string TextWindow_DragAreaTip {
            get {
                return ResourceManager.GetString("TextWindow.DragAreaTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip: Has not enable Japanese text or any translator 的本地化字符串。
        /// </summary>
        public static string TextWindow_EnableFunctionTip {
            get {
                return ResourceManager.GetString("TextWindow.EnableFunctionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Important: Seems like hasn&apos;t set hook yet 的本地化字符串。
        /// </summary>
        public static string TextWindow_SetHookTip {
            get {
                return ResourceManager.GetString("TextWindow.SetHookTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for text... 的本地化字符串。
        /// </summary>
        public static string TextWindow_WaitingForText {
            get {
                return ResourceManager.GetString("TextWindow.WaitingForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaiduApi 的本地化字符串。
        /// </summary>
        public static string Translator_BaiduApi {
            get {
                return ResourceManager.GetString("Translator.BaiduApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaiduWeb 的本地化字符串。
        /// </summary>
        public static string Translator_BaiduWeb {
            get {
                return ResourceManager.GetString("Translator.BaiduWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caiyun 的本地化字符串。
        /// </summary>
        public static string Translator_Caiyun {
            get {
                return ResourceManager.GetString("Translator.Caiyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google Translate (CN) 的本地化字符串。
        /// </summary>
        public static string Translator_GoogleCn {
            get {
                return ResourceManager.GetString("Translator.GoogleCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NiuTrans 的本地化字符串。
        /// </summary>
        public static string Translator_NiuTrans {
            get {
                return ResourceManager.GetString("Translator.NiuTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TencentMt 的本地化字符串。
        /// </summary>
        public static string Translator_TencentMt {
            get {
                return ResourceManager.GetString("Translator.TencentMt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yeekit 的本地化字符串。
        /// </summary>
        public static string Translator_Yeekit {
            get {
                return ResourceManager.GetString("Translator.Yeekit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Youdao 的本地化字符串。
        /// </summary>
        public static string Translator_Youdao {
            get {
                return ResourceManager.GetString("Translator.Youdao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AIUEO song 的本地化字符串。
        /// </summary>
        public static string TransPage_Aiueo {
            get {
                return ResourceManager.GetString("TransPage.Aiueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.youtube.com/watch?v=LrXHizFaol0 的本地化字符串。
        /// </summary>
        public static string TransPage_AiueoLink {
            get {
                return ResourceManager.GetString("TransPage.AiueoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Know some Japanese alphabet can help better understanding! 的本地化字符串。
        /// </summary>
        public static string TransPage_LearnJapaneseTip {
            get {
                return ResourceManager.GetString("TransPage.LearnJapaneseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tae Kim&apos;s Guide to Learning Japanese 的本地化字符串。
        /// </summary>
        public static string TransPage_TaeKimGrammer {
            get {
                return ResourceManager.GetString("TransPage.TaeKimGrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://guidetojapanese.org/learn/grammar/ 的本地化字符串。
        /// </summary>
        public static string TransPage_TaeKimGrammerLink {
            get {
                return ResourceManager.GetString("TransPage.TaeKimGrammerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Translation 的本地化字符串。
        /// </summary>
        public static string TransPage_Title {
            get {
                return ResourceManager.GetString("TransPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string TransPage_To {
            get {
                return ResourceManager.GetString("TransPage.To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string TransPage_TransLabel {
            get {
                return ResourceManager.GetString("TransPage.TransLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string TransPage_TranslatorDetail {
            get {
                return ResourceManager.GetString("TransPage.TranslatorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text to Speech 的本地化字符串。
        /// </summary>
        public static string TTSPage_Title {
            get {
                return ResourceManager.GetString("TTSPage.Title", resourceCulture);
            }
        }
    }
}
